{{ if .Values.microgateway.enabled }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurity
metadata:
  name: adminapp-config-editor-content-security
spec:
  parserRef:
    name: iam-parser
  limitsRef:
    name: iam-limits
  headerRewritesRef:
    name: iam-adminapp-config-editor-header-rewrites

{{ end }}